src/Web/UniversitySystem.Web/Controllers/CourseController.cs
namespace UniversitySystem.Web.Controllers
{
    using System;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;

    using AutoMapper;

    using Business.Services.Contracts;
    using Common;
    using Infrastructure.Filters;
    using Models.Course;

    public class CourseController : Controller
    {
        private readonly ICourseService courseService;
        private readonly IUserService userService;
        private readonly IMapper mapper;

        public CourseController(ICourseService courseService, IUserService userService, IMapper mapper)
        {
            this.courseService = courseService ?? throw new ArgumentNullException(nameof(courseService));
            this.userService = userService ?? throw new ArgumentNullException(nameof(userService));
            this.mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
        }

        /// <summary>
        /// Action for get lists of the course for the user (student)
        /// </summary>
        /// <returns>Return two lists of course, one with registered and one with non-registered for the user (student)</returns>
        [HttpGet]
        [CheckIfUserIsNotLogin(GlobalAccountConstants.ControllerName, GlobalAccountConstants.LoginActionName)]
        public IActionResult GetCourseList()
        {
            var studentId = this.userService.GetUserId(this.User);
            var model = this.courseService.GetCourseListsByStudent(studentId);
            var viewModel = this.mapper.Map<CourseListsByStudentViewModel>(model);

            return this.View(viewModel);
        }

        /// <summary>
        /// Asyncronosly action method for register in course for user 
        /// </summary>
        /// <param name="courseId">Course id</param>
        /// <returns>Return task with parameter action result, parameter is OkResult. In OkResult has result for success of register course for student</returns>
        [HttpPost]
        [IgnoreAntiforgeryToken]
        [CheckIfUserIsNotLoginApi(GlobalAccountConstants.ControllerName, GlobalAccountConstants.LoginActionName)]
        public async Task<IActionResult> RegisterCourse(int courseId)
        {
            var studentId = this.userService.GetUserId(this.User);
            var result = await this.courseService.RegisterStudentAsync(courseId, studentId);
            var viewModelResult = this.mapper.Map<RegisterToCourseViewModel>(result);

            return this.Ok(viewModelResult);
        }

        /// <summary>
        /// Asyncronosly action method for unregister in course for user 
        /// </summary>
        /// <param name="courseId">Course id</param>
        /// <returns>Return task with parameter action result, parameter is OkResult. In OkResult has result for success of unregister course for student</returns>
        [HttpPost]
        [IgnoreAntiforgeryToken]
        [CheckIfUserIsNotLoginApi(GlobalAccountConstants.ControllerName, GlobalAccountConstants.LoginActionName)]
        public async Task<IActionResult> UnRegisterCourse(int courseId)
        {
            var studentId = this.userService.GetUserId(this.User);
            var result = await this.courseService.UnRegisterStudentAsync(courseId, studentId);
            var viewModelResult = this.mapper.Map<UnRegisterToCourseViewModel>(result);

            return this.Ok(viewModelResult);
        }
    }
}

src/Web/UniversitySystem.Web/Controllers/ManageCourseController.cs
namespace UniversitySystem.Web.Controllers
{
    using System;
    using System.Threading.Tasks;
    using System.Linq;
    using Microsoft.AspNetCore.Mvc;

    using AutoMapper;
    using AutoMapper.QueryableExtensions;

    using Business.Services.Contracts;
    using Common;
    using Infrastructure.Filters;
    using Models.Course;
    using Models.ManageCourse;

    public class ManageCourseController : Controller
    {
        private readonly ICourseService courseService;
        private readonly IUserService userService;
        private readonly IMapper mapper;

        public ManageCourseController(ICourseService courseService, IUserService userService, IMapper mapper)
        {
            this.courseService = courseService ?? throw new ArgumentNullException(nameof(courseService));
            this.userService = userService ?? throw new ArgumentNullException(nameof(userService));
            this.mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
        }

        /// <summary>
        /// Asyncronosly action method for add of course
        /// </summary>
        /// <param name="request">Model with name and score of the course</param>
        /// <returns>Return add result</returns>
        [HttpPost]
        [IgnoreAntiforgeryToken]
        [CheckIfUserIsNotLoginApi(GlobalAccountConstants.ControllerName, GlobalAccountConstants.LoginActionName)]
        public async Task<IActionResult> Add(AddCourseViewModel request)
        {
            if (!this.ModelState.IsValid)
            {
                return this.BadRequest();
            }

            var model = await this.courseService.AddAsync(request.Name, request.Score);

            if(model == null)
            {
                return this.Ok(new AddCourseViewModel());
            }

            request.Id = model.Id;
            request.IsSucessfull = true;

            return this.Ok(request);
        }

        /// <summary>
        /// Actin method for update of course
        /// </summary>
        ///<param name="courseId">Course id</param>
        /// <returns>Return view for update</returns>
        [HttpGet]
        [CheckIfUserIsNotLogin(GlobalAccountConstants.ControllerName, GlobalAccountConstants.LoginActionName)]
        public async Task<IActionResult> Update(int courseId)
        {
            var course = await this.courseService.GetAsync(courseId);
            var courseViewModel = this.mapper.Map<CourseViewModel>(course);

            return this.View(courseViewModel);
        }

        /// <summary>
        /// Asyncronosly action method for update of course
        /// </summary>
        /// <param name="request">Model with name, score and id of the course</param>
        /// <returns>Return task with parameter action result, if model is valid, redirect to get all action, otherwise is View for update with error.</returns>
        [HttpPost]
        [CheckIfUserIsNotLogin(GlobalAccountConstants.ControllerName, GlobalAccountConstants.LoginActionName)]
        public async Task<IActionResult> Update(CourseViewModel request)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(request);
            }

            var isSuccess = await this.courseService.UpdateCourseAsync(request.Id, request.Name, request.Score);
            var resultModel = new ResultViewModel(isSuccess);

            return this.RedirectToAction(GlobalManageCourseConstants.GetAllActionName);
        }

        /// <summary>
        /// Asyncronosly action method for delete of course
        /// </summary>
        /// <param name="request">Course id</param>
        /// <returns>Return task with parameter action result, parameter is OkResult. In OkResult has result for success of the delete opeteration</returns>
        [HttpPost]
        [IgnoreAntiforgeryToken]
        [CheckIfUserIsNotLoginApi(GlobalAccountConstants.ControllerName, GlobalAccountConstants.LoginActionName)]
        public async Task<IActionResult> Delete(int courseId)
        {
            var isSuccess = await this.courseService.DeleteAsync(courseId);
            var resultModel = new ResultViewModel(isSuccess);

            return this.Ok(resultModel);
        }

        /// <summary>
        /// Action to get all course
        /// </summary>
        /// <returns>Return all course</returns>
        [HttpGet]
        [CheckIfUserIsNotLogin(GlobalAccountConstants.ControllerName, GlobalAccountConstants.LoginActionName)]
        public IActionResult GetAll()
        {
            var viewModel = this.courseService.GetAll().ProjectTo<CourseDetailViewModel>().ToList();

            return this.View(viewModel);
        }
    }
}

src/Web/UniversitySystem.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UniversitySystem</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li> <a asp-controller="Course" asp-action="GetCourseList">Courses</a></li>
                    <li> <a asp-controller="ManageCourse" asp-action="GetAll">Manage Courses</a></li>

                    @if (!User.Identity.IsAuthenticated)
    {
                <li> <a asp-controller="Account" asp-action="Login">Login</a></li>
                <li> <a asp-controller="Account" asp-action="Register">Register</a></li>
}
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>


    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/notify.min.js"></script>
        <script src="~/js/course.js" asp-append-version="true"></script>
        <script src="~/js/manageCourse.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/lib/jquery/dist/jquery.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/lib/notify.min.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>


    @RenderSection("Scripts", required: false)
</body>
</html>